### ISSUE TITLE
Project settings overwrite user settings

### ISSUE THREAD

**Issue by makao** [hudochenkov/sublime-postcss-sorting#10] opened 2017-07-01 08:03 UTC
Hello,
I have a problem, when I try to override plugin settings for specific project (just sort-on-save option) plugin stops working. It looks like the user settings are overwritten. Steps to reproduce:

Default settings:
```
{
	// Please visit https://github.com/hudochenkov/postcss-sorting#options for all plugin options

	// Set true to sort on save every file with supported syntax
	"sort-on-save": false
}
```
User settings (set some rules):
```
{
    "order": [
        "custom-properties",
        "dollar-variables",
        "at-rules",
        "declarations",
        {
            "type": "at-rule",
            "name": "media"
        },
        "rules"
    ],
    "properties-order": [
        ...
    ],
    "unspecified-properties-position": "bottom"
}
```

And then in specific project just overwrite sort-on-save option
```
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "settings": {
        "PostCSSSorting": {
            "sort-on-save": true
        }
    }
}
```
And now plugin doesn't sort properties, even with executing command, so I suppose that properties order is missing. I think correct behaviour should be just overwrite sort-on-save function, not whole plugin configuration. Currently workaround is to copy all user settings to project settings.

Thanks for the plugin.

**Comment by hudochenkov** [comment] 2017-12-29 23:26
I can't reproduce this behavior. Settings are merged as expected. Can you try the latest version (3.0.0) and see if the problem is resolved?

**Closed as completed** 2018-02-25 21:57 UTC
